---
title: "README"
author: "Justin Peabody"
date: "2026-05-27"
output: html_document
---

Welcome to the repository hosting the code for my summer 2026 Air Quality research! This research was conducted under the Loyola University Undergraduate Summer Research Experience (USRE). I was mentored by Dr. Mena Whalen in the Department of Mathematics and Statistics. 

The project connected me to a SQL database used by a university air quality research lab called the CLEAR lab, which employs students and professors to analyze data from Chicago-based air quality sensors created by the company PurpleAir, install new sensors, and support public education and outreach on  the relevance of PM2.5 (particulate matter measuring less than 2.5 microns in diameter) to public health. 

The database consists of three tables: air_history, which contains readings of PM2.5 concentrations, temperature, pressure, relative humidity, and WiFi connection strength of PurpleAir sensors; and two metadata tables: sensor and sensor_information, which contain each sensor's name, date of creation, date previously online, whether the sensor is indoor or outdoor, its latitude and longitude, and whether or not its data is accessible to the public.

This 4-week-long research experience was designed to familiarize me with the SQL database, introductory SQL querying, and programmatic procedures used by the lab to update the database and connect the SQL server to RStudio. The only two files in this repository are this README and AQ_project_codes. 

At a high level, the research was conducted in this sequence:

Week 1: 

* reading previous academic publications by university professors, which used PurpleAir and AirGradient sensor data to explore relationships between outdoor wildfire smoke levels and indoor PM2.5, utilized statistical and machine learning models incorporating particlate matter concentrations, wind speed, temperature, relative and specific humidity, solar flux, and other meteorological variables to optimize placement of future sensors. This familiarized me with the ways sensor data has been used in previous research.

* learning basic syntax and keywords used in SQL database querying, such as SELECT, WHERE, aggregate functions, etc.

* Connection to the SQL database was delayed by one week due to technical difficulties involving database access permissions. The latter half of Week 1 and the former half of Week 2 involved much troubleshooting with the IT department and Dr. Whalen.

Week 2: 

* Successfully configuring the connection between the SQL database and RStudio. 

* Learning the R workflow for pulling data from the PurpleAir database into R and appending data to the SQL server, then applying this workflow to update the SQL database with over 5 months of recent sensor data. 

*Using the CASE WHEN, IF, ELSE, and ALTER TABLE keywords to append a new column of data to the sensor_information table based on the date when the sensor last transmitted data to the server.

Week 3:

* Using a DELETE query to clean sensor_infomation (the sensor metadata table) to only include sensors in the Chicago area and then remove duplicate sensors.

* Creating a new table, called trigger_pulls, to store metadata on updates to the air_history table, including the number of rows inserted into air_history, a list of sensors with new historical data, the timestamp of the update, and a unique ID distinguishing the update.

* Learning about ER diagrams, incuding entities, relationships, and attribute types, and how to create an ER diagram in order to visually depict the structure and information flow of a database. 

* Creating a new ER diagram for the CLEAR lab database to include the new trigger_pulls table.

* Writing an R script to update the database using the workflow derived from the new ER diagram.

* Running a test-automation of the R script using the Terminal to update the database every night at midnight. 

Week 4:

* Presenting the progress made thus far, including background information on the CLEAR lab and PM2.5, changes made to the database structure, and the high-level workflow of the R script. 







